clone_depth: 10

version: "{build}"

environment:
  matrix:
    - nodejs_version: "0.12"
      platform: x86
    - nodejs_version: "4"
      platform: x64
    - nodejs_version: "4"
      platform: x86
    - nodejs_version: "5"
      platform: x86
    - nodejs_version: "6"
      platform: x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version && npm --version
  - cmd: npm run test-all

build: off

matrix:
  fast_finish: true

cache:
  # If one of the files after the right arrow changes, cache will be skipped
  - 'node_modules -> appveyor.yml,package.json'
