#!/bin/sh
BASEDIR=`dirname "$0"`
PHANTOM=node_modules/.bin/phantomjs
SCRIPTDIR="$BASEDIR/lib/phantomjs-specific"
SCRIPT="$SCRIPTDIR/penthouse.js"
CONFIG="$SCRIPTDIR/config.json"

case `uname` in
    *CYGWIN*) BASEDIR=`cygpath -w "$BASEDIR"`;;
esac

$PHANTOM --config="$CONFIG" "$SCRIPT" "$@"
ret=$?

exit $ret
